# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from rSignalEmitter import rSignalEmitter
from gSignalEmitter import gSignalEmitter
from bSignalEmitter import bSignalEmitter
import networktableHelper
from tableDelegate import tableDelegate
class Ui_MainWindow(tableDelegate):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1351, 1009)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rValueDisplay= QtWidgets.QLabel(self.centralwidget)
        self.rValueDisplay.setGeometry(QtCore.QRect(80, 70, 141, 41))
        self.rValueDisplay.setObjectName("rValueDisplay")
        self.gValueDisplay= QtWidgets.QLabel(self.centralwidget)
        self.gValueDisplay.setGeometry(QtCore.QRect(80, 130, 141, 41))
        self.gValueDisplay.setObjectName("gValueDisplay")
        self.bValueDisplay= QtWidgets.QLabel(self.centralwidget)
        self.bValueDisplay.setGeometry(QtCore.QRect(80, 190, 141, 41))
        self.bValueDisplay.setObjectName("bValueDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1351, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.networktable = networktableHelper.networktableHelper(self)
        self.rSignalEmitter = rSignalEmitter()
        self.rSignalEmitter.rSignal.connect(self.updateR)
        self.gSignalEmitter = gSignalEmitter()
        self.gSignalEmitter.gSignal.connect(self.updateG)
        self.bSignalEmitter = bSignalEmitter()
        self.bSignalEmitter.bSignal.connect(self.updateB)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def updateR(self, value):
        self.rValueDisplay.setText(value)
    def updateG(self, value):
        self.gValueDisplay.setText(value)
    def updateB(self, value):
        self.bValueDisplay.setText(value)
    def rChange(self, value):
        print("R: "+value)
        self.rSignalEmitter.rSignal.emit(value)
    def gChange(self, value):
        print("G: "+value)
        self.gSignalEmitter.gSignal.emit(value)
    def bChange(self, value):
        print("B: "+value)
        self.bSignalEmitter.bSignal.emit(value)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
